#!/usr/bin/env python3
"""
code_arc_v2 - Python Code Architecture Visualizer (tree-layout edition)

Usage:
    python -m code_arc_v2 <project_path> <structure_html> [output.html]

Examples:
    python -m code_arc_v2 ./my_project ./my_project_structure.html
    python -m code_arc_v2 ./my_project ./my_project_structure.html vis.html

The <structure_html> file is a "component structure" diagram (packages + modules)
generated by feeding your project to the reusable LLM prompt in README.md.
"""

import sys

from . import visualize


def main():
    if len(sys.argv) < 3:
        print("Usage: python -m code_arc_v2 <project_path> <structure_html> [output.html]")
        print("")
        print("Arguments:")
        print("  project_path    Path to the Python project directory")
        print("  structure_html  Reference component-structure HTML (see README prompt)")
        print("  output.html     Output HTML file path (default: code_arc_v2_output.html)")
        sys.exit(1)

    project_path = sys.argv[1]
    structure_html = sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) > 3 else "code_arc_v2_output.html"

    visualize(project_path, structure_html, output_path)


if __name__ == "__main__":
    main()
